;;; check-git-workflows.el --- Git workflow checks -*- lexical-binding: t; coding: utf-8; -*-
(load (or (getenv "NEO_GIT_WORKFLOW_SOURCE")
          (expand-file-name "neo-git.el" (file-name-directory load-file-name))) nil t)
(require 'cl-lib)

(defun neo-git-workflow-output (root &rest args)
  (with-temp-buffer
    (let ((coding-system-for-read 'utf-8-unix)
          (coding-system-for-write (if (eq system-type 'windows-nt)
                                       w32-system-coding-system 'utf-8-unix)))
      (let ((status (apply #'process-file (neo-git--executable) nil t nil "-C" root args)))
        (cl-assert (zerop status) nil "Git %S exit %s: %s" args status (buffer-string)))
      (string-trim (buffer-string)))))

(defun neo-git-workflow-wait (predicate)
  (let ((deadline (+ (float-time) 15)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil 0.02))
    (cl-assert (funcall predicate))))

(let* ((root (file-name-as-directory (make-temp-file "neo-git-workflows-" t)))
       (global-config (make-temp-file "neo-git-workflow-global-"))
       (default-directory root)
       (process-environment (copy-sequence process-environment))
       (owner (generate-new-buffer " *workflow-owner*"))
       file-buffer history stash preview)
  (setenv "GIT_CONFIG_GLOBAL" global-config)
  (setenv "GIT_CONFIG_NOSYSTEM" "1")
  (unwind-protect
      (progn
        (neo-git-workflow-output root "init" "-q" "-b" "main")
        (neo-git-workflow-output root "config" "user.name" "Workflow Check")
        (neo-git-workflow-output root "config" "user.email" "check@example.invalid")
        (with-temp-file "file.txt" (insert "baseline\n"))
        (neo-git-workflow-output root "add" "file.txt")
        (neo-git-workflow-output root "commit" "-qm" "initial 日本語")
        (neo-git-workflow-output root "switch" "-qc" "side")
        (with-temp-file "side.txt" (insert "side\n"))
        (neo-git-workflow-output root "add" "side.txt")
        (neo-git-workflow-output root "commit" "-qm" "side work")
        (neo-git-workflow-output root "switch" "-q" "main")
        (neo-git-workflow-output root "merge" "-q" "--no-ff" "-m" "merge side" "side")
        (with-current-buffer owner
          (neo-git-mode)
          (setq neo-git-root root neo-git-state '(:branch "main"))
          (cl-letf (((symbol-function 'pop-to-buffer) #'set-buffer))
            (neo-git-history))
          (setq history (current-buffer)))
        (neo-git-workflow-wait
         (lambda () (with-current-buffer history tabulated-list-entries)))
        (with-current-buffer history
          (goto-char (point-min))
          (cl-assert (string-match-p "initial 日本語" (buffer-string)))
          ;; One row per commit: a hollow merge node pulls in the side lane,
          ;; which forks off the initial commit.
          (cl-assert (string-match-p "^ *○<┐.*(HEAD -> main) merge side" (buffer-string)))
          (cl-assert (string-match-p "^ *│ ●.*side work" (buffer-string)))
          (cl-assert (string-match-p "^ *●─┘.*initial" (buffer-string)))
          (cl-assert (= 3 (length tabulated-list-entries)))
          (cl-assert (seq-every-p #'car tabulated-list-entries))
          (goto-char (point-max))
          (forward-line -1)
          (cl-letf (((symbol-function 'pop-to-buffer) #'set-buffer))
            (neo-git-browser-show))
          (setq preview (current-buffer)))
        (neo-git-workflow-wait
         (lambda () (with-current-buffer preview (string-match-p "+baseline" (buffer-string)))))
        (setq file-buffer (find-file-noselect (expand-file-name "file.txt" root)))
        (with-current-buffer file-buffer (goto-char (point-max)) (insert "unsaved\n"))
        (let (rejected)
          (condition-case nil
              (with-current-buffer owner (neo-git--worktree-ready))
            (user-error (setq rejected t)))
          (cl-assert rejected))
        (with-current-buffer file-buffer (set-buffer-modified-p nil) (revert-buffer t t))
        (with-current-buffer owner
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "topic-日本語")))
            (neo-git-create-branch)))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--mutation owner))))
        (cl-assert (equal "topic-日本語" (neo-git-workflow-output root "branch" "--show-current")))
        (with-current-buffer owner
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "main")))
            (neo-git-switch-branch)
            (neo-git-workflow-wait
             (lambda () (and (not neo-git--mutation)
                             (equal "main" (neo-git-workflow-output root "branch" "--show-current")))))))
        (with-temp-file "file.txt" (insert "changed\n"))
        (neo-git-workflow-output root "add" "file.txt")
        (with-temp-file "new.txt" (insert "untracked\n"))
        (with-current-buffer owner
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "stash 日本語"))
                    ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
            (neo-git-stash-save)))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--mutation owner))))
        (cl-assert (not (file-exists-p "new.txt")))
        (with-current-buffer file-buffer (cl-assert (equal (buffer-string) "baseline\n")))
        (with-current-buffer owner
          (cl-letf (((symbol-function 'pop-to-buffer) #'set-buffer)) (neo-git-stash-list))
          (setq stash (current-buffer)))
        (neo-git-workflow-wait
         (lambda () (with-current-buffer stash tabulated-list-entries)))
        (with-current-buffer stash
          (goto-char (point-min))
          (neo-git-stash-apply))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--mutation owner))))
        (cl-assert (file-exists-p "new.txt"))
        (cl-assert (string-match-p "+changed" (neo-git-workflow-output root "diff" "--cached")))
        (with-current-buffer file-buffer (cl-assert (equal (buffer-string) "changed\n")))
        (cl-assert (not (string-empty-p (neo-git-workflow-output root "stash" "list"))))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--browser-process stash))))
        ;; A stale stash row must never delete a different entry.
        (neo-git-workflow-output root "stash" "push" "-u" "-m" "newer")
        (with-current-buffer stash
          (goto-char (point-min))
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (neo-git-stash-drop)))
        (neo-git-workflow-wait
         (lambda () (seq-some (lambda (entry) (and (equal (plist-get entry :arguments)
                                                          '("rev-parse" "--verify" "stash@{0}"))
                                                   (not (eq (plist-get entry :status) 'running))))
                              (gethash (neo-git--log-key root) neo-git--command-logs))))
        (cl-assert (= 2 (length (split-string (neo-git-workflow-output root "stash" "list") "\n" t))))
        ;; Applying onto conflicting local edits must leave both edits and stash intact.
        (with-current-buffer file-buffer (revert-buffer t t))
        (with-temp-file "file.txt" (insert "local conflict\n"))
        (with-current-buffer stash (goto-char (point-min)) (neo-git-stash-apply))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--mutation owner))))
        (cl-assert (buffer-local-value 'neo-git--last-error owner))
        (cl-assert (equal "local conflict" (with-temp-buffer
                                             (insert-file-contents "file.txt")
                                             (string-trim (buffer-string)))))
        (cl-assert (= 2 (length (split-string (neo-git-workflow-output root "stash" "list") "\n" t))))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--browser-process stash))))
        (with-current-buffer stash
          (goto-char (point-min))
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
            (neo-git-stash-drop)))
        (cl-assert (= 2 (length (split-string (neo-git-workflow-output root "stash" "list") "\n" t))))
        (with-current-buffer stash
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (neo-git-stash-drop)))
        (neo-git-workflow-wait
         (lambda () (= 1 (length (split-string (neo-git-workflow-output root "stash" "list") "\n" t)))))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--mutation owner))))
        (neo-git-workflow-wait (lambda () (not (buffer-local-value 'neo-git--browser-process stash))))
        ;; Merge conflict: markers block staging; resolve, stage and continue.
        (neo-git-workflow-output root "reset" "-q" "--hard")
        (neo-git-workflow-output root "clean" "-fdq")
        (with-current-buffer file-buffer (revert-buffer t t))
        (neo-git-workflow-output root "switch" "-qc" "theirs")
        (with-temp-file "file.txt" (insert "theirs\n"))
        (neo-git-workflow-output root "commit" "-qam" "theirs")
        (neo-git-workflow-output root "switch" "-q" "main")
        (with-temp-file "file.txt" (insert "ours\n"))
        (neo-git-workflow-output root "commit" "-qam" "ours")
        (with-current-buffer owner
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "theirs")))
            (neo-git-merge))
          (neo-git-workflow-wait
           (lambda () (and (not neo-git--mutation) (not neo-git--status-updating)
                           (seq-find (lambda (e) (eq (plist-get e :kind) 'conflict))
                                     neo-git-entries))))
          (cl-assert (equal "merge" (neo-git--in-progress-p)))
          (let ((conflict (seq-find (lambda (e) (eq (plist-get e :kind) 'conflict))
                                    neo-git-entries))
                rejected)
            (condition-case nil (neo-git--stage-entries (list conflict))
              (user-error (setq rejected t)))
            (cl-assert rejected)
            (with-temp-file "file.txt" (insert "resolved\n"))
            (neo-git--stage-entries (list conflict)))
          (neo-git-workflow-wait (lambda () (not neo-git--mutation)))
          (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?c)))
            (neo-git-continue))
          (neo-git-workflow-wait (lambda () (not neo-git--mutation)))
          (cl-assert (not (neo-git--in-progress-p)))
          (cl-assert (= 2 (length (split-string (neo-git-workflow-output
                                                 root "log" "-1" "--format=%P"))))))
        (with-current-buffer file-buffer (cl-assert (equal (buffer-string) "resolved\n")))
        ;; A conflicting cherry-pick can be aborted back to the previous state.
        (neo-git-workflow-output root "switch" "-qc" "pick" "main~1")
        (with-temp-file "file.txt" (insert "picked\n"))
        (neo-git-workflow-output root "commit" "-qam" "pick me")
        (let ((oid (neo-git-workflow-output root "rev-parse" "HEAD")))
          (neo-git-workflow-output root "switch" "-q" "main")
          (with-current-buffer history
            (cl-letf (((symbol-function 'tabulated-list-get-id) (lambda (&rest _) oid))
                      ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
              (neo-git-cherry-pick))))
        (with-current-buffer owner
          (neo-git-workflow-wait (lambda () (not neo-git--mutation)))
          (cl-assert (equal "cherry-pick" (neo-git--in-progress-p)))
          (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?a))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (neo-git-continue))
          (neo-git-workflow-wait (lambda () (not neo-git--mutation)))
          (cl-assert (not (neo-git--in-progress-p))))
        (with-current-buffer file-buffer (cl-assert (equal (buffer-string) "resolved\n")))
        ;; Rebase the current branch onto another one.
        (neo-git-workflow-output root "switch" "-qc" "topic" "main~1")
        (with-temp-file "topic.txt" (insert "topic\n"))
        (neo-git-workflow-output root "add" "topic.txt")
        (neo-git-workflow-output root "commit" "-qm" "topic")
        (with-current-buffer owner
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "main")))
            (neo-git-rebase))
          (neo-git-workflow-wait (lambda () (not neo-git--mutation))))
        (neo-git-workflow-output root "merge-base" "--is-ancestor" "main" "HEAD")
        (neo-git-workflow-output root "switch" "-q" "main")
        (princ "NEO_GIT_WORKFLOWS=PASS\n"))
    (dolist (buffer (list file-buffer history stash preview owner))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer)))
    (delete-directory root t)
    (delete-file global-config)))
