;;; check-git.el --- Neo Git checks -*- lexical-binding: t; coding: utf-8; -*-
(load (expand-file-name "neo-git.el" (file-name-directory load-file-name)) nil t)
(load (expand-file-name "benchmark-git.el" (file-name-directory load-file-name)) nil t)
(require 'cl-lib)
(require 'json)
(neo-git-benchmark-start)

(defun neo-git-check-call (&rest arguments)
  (let ((status (apply #'process-file (neo-git--executable) nil nil nil arguments)))
    (unless (and (integerp status) (zerop status))
      (error "Git check failed (%S): %S" status arguments))))

(defun neo-git-check-wait (predicate)
  (let ((deadline (+ (float-time) 15)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil 0.05))
    (unless (funcall predicate)
      (error "Timed out waiting for Neo Git"))))

(defun neo-git-check-output (&rest arguments)
  (with-temp-buffer
    (let* ((coding-system-for-read 'utf-8-unix)
           (status (apply #'process-file (neo-git--executable) nil t nil arguments)))
      (unless (and (integerp status) (zerop status))
        (error "Git check failed (%S): %S: %s" status arguments (buffer-string)))
      (buffer-string))))

(defun neo-git-check-bytes (&rest arguments)
  (with-temp-buffer
    (set-buffer-multibyte nil)
    (let* ((coding-system-for-read 'no-conversion)
           (status (apply #'process-file (neo-git--executable) nil t nil arguments)))
      (unless (and (integerp status) (zerop status))
        (error "Git byte check failed (%S): %S" status arguments))
      (buffer-string))))

(defun neo-git-check-file-bytes (file)
  (with-temp-buffer
    (set-buffer-multibyte nil)
    (insert-file-contents-literally file)
    (buffer-string)))

(defun neo-git-check-write-utf8 (file text)
  (let ((coding-system-for-write 'no-conversion))
    (write-region (encode-coding-string text 'utf-8-unix) nil file nil 'silent)))

(defun neo-git-check-apply-patch (root patch reverse &optional worktree)
  (let ((file (make-temp-file "neo-git-check-patch-"))
        (coding-system-for-write 'utf-8-unix))
    (unwind-protect
        (progn
          (write-region patch nil file nil 'silent)
          (apply #'neo-git-check-call
                 (append (list "-C" root "apply" "--whitespace=nowarn")
                         (unless worktree (list "--cached"))
                         (when reverse (list "--reverse"))
                         (list file))))
      (when (file-exists-p file)
        (delete-file file)))))

(defun neo-git-check-multi-selection-dispatch ()
  (with-temp-buffer
    (neo-git-mode)
    (transient-mark-mode 1)
    (setq neo-git-root default-directory
          neo-git-state '(:oid "head")
          neo-git-entries '((:path "first.txt" :kind unstaged)
                            (:path "second [literal].txt" :kind unstaged)
                            (:path "third.txt" :kind unstaged)))
    (neo-git--render)
    (let (arguments)
      (cl-letf (((symbol-function 'neo-git--mutate)
                 (lambda (args &rest _) (setq arguments args))))
        (let ((rows (neo-git--row-positions)))
          (goto-char (car rows))
          (set-mark (car rows))
          (goto-char (nth 1 rows))
          (setq neo-git--visual-inclusive t)
          (setq mark-active t)
          (neo-git-stage-toggle))
        (cl-assert (equal arguments
                          '("add" "--" ":(literal)first.txt"
                            ":(literal)second [literal].txt")) nil
                   "Multi-selection args=%S region=%S selected=%S"
                   arguments (use-region-p) (neo-git--selected-entries))))))
(neo-git-check-multi-selection-dispatch)

(defun neo-git-check-refresh-coalescing ()
  (let ((calls 0)
        callbacks)
    (with-temp-buffer
      (neo-git-mode)
      (setq neo-git-root default-directory)
      (setq neo-git-state '(:branch "before"))
      (setq neo-git-entries
            '((:path "first.txt" :kind unstaged)
              (:path "second.txt" :kind unstaged)))
      (neo-git--render)
      (cl-letf (((symbol-function 'neo-git--refresh-attributes) (lambda (&rest _) nil))
                ((symbol-function 'neo-git--run)
                 (lambda (_directory _arguments callback &optional _limit)
                   (cl-incf calls)
                   (push callback callbacks)
                   'neo-git-check-process))
                ((symbol-function 'process-live-p)
                 (lambda (process)
                   (eq process 'neo-git-check-process)))
                ((symbol-function 'delete-process) (lambda (_process)
                                                     nil)))
        (neo-git-refresh)
        (cl-assert (= calls 1) nil "Refresh should start status immediately")
        (cl-assert (null neo-git--refresh-timer))
        (neo-git-next)
        (cl-assert (equal (plist-get (neo-git--entry-at-point) :path) "second.txt"))
        (dotimes (_ 5)
          (neo-git-refresh))
        (cl-assert (= calls 1) nil "In-flight refreshes should coalesce")
        (cl-assert neo-git--refresh-pending)
        (funcall (car callbacks) 0 "# branch.head stale\0" "")
        (cl-assert (= calls 2) nil "A burst should queue exactly one fresh status")
        (cl-assert (equal (plist-get neo-git-state :branch) "before")
                   nil "Do not render a superseded status")
        (cl-assert (null neo-git--refresh-pending))
        (cl-assert (null neo-git--refresh-timer))
        (funcall (car callbacks)
                 0 (concat "# branch.head main\0"
                           "1 .M N... 100644 100644 100644 abc def first.txt\0"
                           "1 .M N... 100644 100644 100644 abc def second.txt\0") "")
        (cl-assert (equal (plist-get neo-git-state :branch) "main"))
        (cl-assert (equal (plist-get (neo-git--entry-at-point) :path) "second.txt")
                   nil "Refresh should preserve selection movement during the query")
        (cl-assert (= calls 2))
        (cl-assert (null neo-git--refresh-process))))))

(neo-git-check-refresh-coalescing)

(defun neo-git-check-rendering ()
  (with-temp-buffer
    (neo-git-mode)
    (setq neo-git-root "C:/fixture/"
          neo-git-state '(:branch "color-branch")
          neo-git-entries '((:path "modified.txt" :kind unstaged)
                            (:path "second.txt" :kind unstaged)
                            (:path "new.txt" :kind untracked)
                            (:path "ready.txt" :kind staged)
                            (:path "conflict.txt" :kind conflict)))
    (neo-git--render)
    (dolist (header '("Changes (2)" "Untracked (1)" "Staged (1)" "Conflicts (1)"))
      (cl-assert (string-match-p (regexp-quote header) (buffer-string))))
    (dolist (pair '( ("modified.txt" . ("UNSTAGED" . neo-git-unstaged-face))
                     ("new.txt" . ("UNTRACKED" . neo-git-untracked-face))
                     ("ready.txt" . ("STAGED" . neo-git-staged-face))
                     ("conflict.txt" . ("CONFLICT" . neo-git-conflict-face))))
      (goto-char (point-min))
      (search-forward (car pair))
      (beginning-of-line)
      (cl-assert (search-forward (car (cdr pair)) (line-end-position) t))
      (cl-assert (eq (get-text-property (+ (line-beginning-position) 2) 'face)
                     (cdr (cdr pair)))
                 nil "Status label and row should carry the matching state face")
      (cl-assert (get-text-property (line-beginning-position) 'neo-git-entry)))
    (goto-char (point-min))
    (search-forward "color-branch")
    (cl-assert (eq (get-text-property (1- (point)) 'face) 'neo-git-branch-face))
    (cl-assert (and hl-line-mode hl-line-sticky-flag (overlayp hl-line-overlay)))
    (let ((owner (current-buffer))
          (preview (generate-new-buffer " *neo-git-render-check*")))
      (unwind-protect
          (with-current-buffer preview
            (setq-local neo-git--diff-owner owner)
            (neo-git--owner-next)
            (with-current-buffer owner
              (cl-assert (= (overlay-start hl-line-overlay)
                            (line-beginning-position)))))
        (kill-buffer preview)))))
(neo-git-check-rendering)

(with-temp-buffer
  (neo-git-mode)
  (setq neo-git--mutation t
        neo-git--mutation-label "Review 25% hook"
        neo-git--progress-start (float-time)
        neo-git--progress-detail "review progress 25%")
  (let ((header (neo-git--status-header-line)))
    (cl-assert (string-match-p "Review 25%% hook" header)
               nil "Status header must escape target labels for mode-line formatting")
    (cl-assert (string-match-p "review progress 25%%" header)
               nil "Status header must escape Git progress for mode-line formatting"))
  (let ((owner (current-buffer))
        (preview (generate-new-buffer " *neo-git-percent-check*")))
    (unwind-protect
        (with-current-buffer preview
          (setq-local neo-git--diff-owner owner)
          (let ((header (neo-git--diff-header-line)))
            (cl-assert (string-match-p "Review 25%% hook" header)
                       nil "Diff header must escape target labels for mode-line formatting")
            (cl-assert (string-match-p "review progress 25%%" header)
                       nil "Diff header must escape Git progress for mode-line formatting")))
      (kill-buffer preview))))

(let* ((directory (file-name-as-directory (make-temp-name "neo-git-log-check-")))
       (entry (neo-git--log-start directory '("commit" "-m" "check")))
       (long-output (concat (make-string 5000 ?a) "fatal: retained tail")))
  (neo-git--log-finish entry 1 "" long-output)
  (let ((stored (car (gethash (neo-git--log-key directory) neo-git--command-logs))))
    (cl-assert (numberp (plist-get stored :elapsed)) nil
               "Finished command log must retain elapsed time")
    (cl-assert (equal (plist-get stored :finished) (plist-get entry :finished)))
    (cl-assert (<= (length (plist-get stored :stderr)) neo-git--log-text-limit))
    (cl-assert (string-match-p "fatal: retained tail" (plist-get stored :stderr)) nil
               "Log clipping must preserve the end of long progress output")))

(let* ((state (neo-git--parse-status
               (concat "# branch.head main\0# branch.upstream origin/main\0"
                       "# branch.ab +2 -1\0"
                       "1 .M N... 100644 100644 100644 abc def spaced name.txt\0"
                       "1 MM N... 100644 100644 100644 abc def partial staged.txt\0"
                       "2 R. N... 100644 100644 100644 abc def R100 new name.txt\0old name.txt\0"
                       "u UU N... 100644 100644 100644 100644 abc def ghi conflict name.txt\0"
                       "? 日本語 file.txt\0? line\nbreak\tfile\0")))
       (entries (plist-get state :entries)))
  (cl-assert (equal (plist-get state :branch) "main"))
  (cl-assert (equal (plist-get state :upstream) "origin/main"))
  (cl-assert (= (plist-get state :ahead) 2))
  (cl-assert (= (plist-get state :behind) 1))
  (cl-assert (equal (plist-get (car entries) :path) "spaced name.txt"))
  (cl-assert (eq (plist-get (car entries) :kind) 'unstaged))
  (let ((japanese (cl-find "日本語 file.txt" entries
                           :key (lambda (entry)
                                  (plist-get entry :path)) :test #'equal))
        (partial (cl-find "partial staged.txt" entries
                          :key (lambda (entry)
                                 (plist-get entry :path)) :test #'equal))
        (rename (cl-find "new name.txt" entries
                         :key (lambda (entry)
                                (plist-get entry :path)) :test #'equal))
        (conflict (cl-find "conflict name.txt" entries
                           :key (lambda (entry)
                                  (plist-get entry :path)) :test #'equal))
        (newline (cl-find "line\nbreak\tfile" entries
                          :key (lambda (entry)
                                 (plist-get entry :path)) :test #'equal)))
    (cl-assert (eq (plist-get japanese :kind) 'untracked))
    (cl-assert (= 2 (cl-count "partial staged.txt" entries
                              :key (lambda (entry)
                                     (plist-get entry :path)) :test #'equal)))
    (cl-assert (equal (plist-get rename :old-path) "old name.txt"))
    (cl-assert (eq (plist-get conflict :kind) 'conflict))
    (cl-assert (eq (plist-get newline :kind) 'untracked))))

(let* ((root (make-temp-file "neo-git-check-" t))
       (default-directory (file-name-as-directory root))
       (name "tracked file.txt")
       (status-buffer nil))
  (unwind-protect
      (progn
        (neo-git-check-call "init" "-q")
        (neo-git-check-call "config" "user.name" "Neo Git Check")
        (neo-git-check-call "config" "user.email" "neo-git-check@example.invalid")
        (neo-git-check-call "config" "commit.gpgsign" "false")
        (neo-git-check-call "config" "core.quotepath" "false")
        (with-temp-file name (insert "base\n"))
        (with-temp-file "next-work.txt" (insert "base\n"))
        (with-temp-file "source.txt" (insert "rename source\n"))
        (with-temp-file "deleted.txt" (insert "delete source\n"))
        (neo-git-check-call "add" "--" name "next-work.txt" "source.txt" "deleted.txt")
        (neo-git-check-call "commit" "-qm" "initial")
        (with-temp-file name (insert "base\nchanged\n"))
        (with-temp-file "next-work.txt" (insert "base\nnext work item\n"))
        (setq status-buffer (format "*Neo Git: %s*" (directory-file-name root)))
        (neo-git-status)
        (neo-git-check-wait
         (lambda ()
           (and (get-buffer status-buffer)
                (with-current-buffer status-buffer
                  (and neo-git-state (not neo-git--refresh-process)
                       (not neo-git--refresh-timer))))))
        (with-current-buffer status-buffer
          (cl-assert (eq major-mode 'neo-git-mode))
          (cl-assert (equal (plist-get neo-git-state :branch)
                            (string-trim (car (process-lines (neo-git--executable) "-C" root "branch" "--show-current")))))
          (goto-char (point-min))
          (search-forward name)
          (beginning-of-line)
          (cl-assert (eq (plist-get (neo-git--entry-at-point) :kind) 'unstaged))
          (setq neo-git--preview-buffer (get-buffer-create "*Neo Git Check Diff*"))
          (neo-git--preview-selected)
          (neo-git-check-wait (lambda ()
                                (not neo-git--diff-process)))
          (with-current-buffer neo-git--preview-buffer
            (cl-assert (string-match-p "\+changed" (buffer-string))))
          (neo-git-stage-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (unless (seq-some (lambda (entry)
                              (eq (plist-get entry :kind) 'staged)) neo-git-entries)
            (error "Stage missing: last-error=%S entries=%S status=%S" neo-git--last-error neo-git-entries
                   (with-temp-buffer
                     (process-file (neo-git--executable) nil t nil "-C" root
                                   "status" "--porcelain=v2" "-z" "--branch" "--untracked-files=all")
                     (buffer-string))))
          (cl-assert (equal (plist-get (neo-git--entry-at-point) :path) "next-work.txt") nil
                     "Staging should keep selection on the next work-side file")
          (cl-assert (eq (plist-get (neo-git--entry-at-point) :kind) 'unstaged))
          ;; Literal pathspecs must stage unusual but valid Windows filenames as one file.
          (with-temp-file "[literal] name.txt" (insert "literal path\n"))
          (neo-git-refresh)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (seq-some (lambda (entry)
                                                 (and (equal (plist-get entry :path) "[literal] name.txt")
                                                      (eq (plist-get entry :kind) 'untracked)))
                                               neo-git-entries))))
          (goto-char (cl-find-if (lambda (position)
                                   (equal (plist-get (get-text-property position 'neo-git-entry) :path)
                                          "[literal] name.txt"))
                                 (neo-git--row-positions)))
          (neo-git-stage-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (cl-assert (seq-some (lambda (entry)
                                 (and (equal (plist-get entry :path) "[literal] name.txt")
                                      (eq (plist-get entry :kind) 'staged)))
                               neo-git-entries))
          (goto-char (cl-find-if (lambda (position)
                                   (let ((entry (get-text-property position 'neo-git-entry)))
                                     (and (equal (plist-get entry :path) "[literal] name.txt")
                                          (eq (plist-get entry :kind) 'staged))))
                                 (neo-git--row-positions)))
          (neo-git-stage-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (cl-assert (seq-some (lambda (entry)
                                 (and (equal (plist-get entry :path) "[literal] name.txt")
                                      (eq (plist-get entry :kind) 'untracked)))
                               neo-git-entries))
          ;; Staging a rename and toggling it off restores both index paths.
          (neo-git-check-call "-C" root "mv" "source.txt" "renamed [literal].txt")
          (neo-git-refresh)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (seq-some (lambda (entry)
                                                 (and (equal (plist-get entry :path) "renamed [literal].txt")
                                                      (plist-get entry :old-path)))
                                               neo-git-entries))))
          (let ((position (cl-find-if (lambda (position)
                                        (equal (plist-get (get-text-property position 'neo-git-entry) :path)
                                               "renamed [literal].txt"))
                                      (neo-git--row-positions))))
            (goto-char position)
            (neo-git-stage-toggle)
            (neo-git-check-wait (lambda ()
                                  (and (not neo-git--mutation)
                                       (not neo-git--refresh-process)
                                       (not neo-git--refresh-timer))))
            (let ((cached (process-lines (neo-git--executable) "-C" root "diff" "--cached" "--name-status")))
              (cl-assert (equal cached '("M\ttracked file.txt")) nil
                         "Cached=%S last-error=%S entries=%S" cached neo-git--last-error neo-git-entries))
            (cl-assert (equal (with-temp-buffer
                                (insert-file-contents "renamed [literal].txt")
                                (buffer-string)) "rename source\n")))
          ;; Reject a second mutation while the serialized operation slot is occupied.
          (setq neo-git--mutation t)
          (let ((rejected nil))
            (condition-case nil (neo-git-stage-toggle) (user-error (setq rejected t)))
            (cl-assert rejected))
          (setq neo-git--mutation nil)
          ;; A staged deletion can be toggled back to an unstaged deletion.
          (delete-file (expand-file-name "deleted.txt" root))
          (neo-git-refresh)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (seq-some (lambda (entry)
                                                 (and (equal (plist-get entry :path) "deleted.txt")
                                                      (eq (plist-get entry :kind) 'unstaged)))
                                               neo-git-entries))))
          (goto-char (cl-find-if (lambda (position)
                                   (equal (plist-get (get-text-property position 'neo-git-entry) :path) "deleted.txt"))
                                 (neo-git--row-positions)))
          (neo-git-stage-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (cl-assert (not (file-exists-p (expand-file-name "deleted.txt" root))))
          (goto-char (cl-find-if (lambda (position)
                                   (let ((entry (get-text-property position 'neo-git-entry)))
                                     (and (equal (plist-get entry :path) "deleted.txt")
                                          (eq (plist-get entry :kind) 'staged))))
                                 (neo-git--row-positions)))
          (neo-git-stage-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (cl-assert (not (member "deleted.txt" (process-lines (neo-git--executable) "-C" root
                                                               "diff" "--cached" "--name-only"))))
          ;; A same-file staged and unstaged pair remains independently visible.
          (with-temp-file name (insert "base\nchanged\nworking tree only\n"))
          (neo-git-refresh)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (seq-some (lambda (entry)
                                                 (eq (plist-get entry :kind) 'unstaged))
                                               neo-git-entries))))
          (cl-assert (= 2 (cl-count name neo-git-entries
                                    :key (lambda (entry)
                                           (plist-get entry :path)) :test #'equal)))
          (let ((kinds (mapcar (lambda (entry)
                                 (and (equal (plist-get entry :path) name)
                                      (plist-get entry :kind)))
                               neo-git-entries)))
            (cl-assert (memq 'staged kinds))
            (cl-assert (memq 'unstaged kinds)))
          ;; Stage all, then unstage all while keeping the working file intact.
          (neo-git-stage-all-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                      (seq-every-p (lambda (entry)
                                                     (eq (plist-get entry :kind) 'staged))
                                                   neo-git-entries))))
          (cl-assert (null (neo-git--entry-at-point)) nil
                     "Stage-all should leave the empty Changes group selected")
          (cl-assert (eq (get-text-property (line-beginning-position) 'neo-git-group)
                         'unstaged))
          (let ((rejected nil))
            (condition-case nil (neo-git-stage-toggle) (user-error (setq rejected t)))
            (cl-assert rejected nil "Space on an empty source group must not unstage the file"))
          (neo-git-stage-all-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (seq-some (lambda (entry)
                                                 (eq (plist-get entry :kind) 'unstaged))
                                               neo-git-entries))))
          (cl-assert (equal (with-temp-buffer
                              (insert-file-contents name)
                              (buffer-string))
                            "base\nchanged\nworking tree only\n"))
          (cl-assert (null (neo-git--entry-at-point)) nil
                     "Unstage-all should leave the empty Staged group selected")
          (cl-assert (eq (get-text-property (line-beginning-position) 'neo-git-group)
                         'staged))
          ;; Failed hooks retain the message; success commits staged contents only.
          (neo-git-stage-all-toggle)
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer))))
          (neo-git-commit)
          (let ((commit-buffer (current-buffer))
                (hook (expand-file-name ".git/hooks/pre-commit" root)))
            (with-current-buffer commit-buffer
              (insert "保存された日本語 message"))
            (with-temp-file hook (insert "#!/bin/sh\nexit 1\n"))
            (neo-git-commit-finish)
            (with-current-buffer status-buffer
              (neo-git-check-wait (lambda ()
                                    (not neo-git--mutation))))
            (cl-assert (buffer-live-p commit-buffer))
            (with-current-buffer commit-buffer
              (cl-assert (string-prefix-p "保存された日本語 message\n\n# " (buffer-string)))
              (cl-assert (string-match-p "^#\t.+$" (buffer-string))))
            (delete-file hook)
            (neo-git-commit-finish)
            (neo-git-check-wait (lambda ()
                                  (not (buffer-live-p commit-buffer))))
            (cl-assert (equal (string-trim (car (process-lines (neo-git--executable) "-C" root
                                                               "log" "-1" "--format=%s")))
                              "保存された日本語 message")))
          ;; Fetch, pull and push stay inside a local bare remote and clone.
          (with-current-buffer status-buffer
            (let* ((branch (car (process-lines (neo-git--executable) "-C" root "branch" "--show-current")))
                   (remote (expand-file-name "remote.git" root))
                   (clone (expand-file-name "clone" root)))
              (neo-git-check-call "init" "--bare" "-q" remote)
              (neo-git-check-call "remote" "add" "origin" remote)
              (neo-git-check-call "push" "-u" "origin" branch)
              (neo-git-check-call "clone" "-q" remote clone)
              (neo-git-check-call "-C" clone "config" "user.name" "Neo Git Check")
              (neo-git-check-call "-C" clone "config" "user.email" "neo-git-check@example.invalid")
              (neo-git-check-call "-C" clone "config" "commit.gpgsign" "false")
              ;; Push through the UI using the configured upstream.
              (with-temp-file "outgoing.txt" (insert "from local\n"))
              (neo-git-check-call "add" "--" "outgoing.txt")
              (neo-git-check-call "commit" "-qm" "outgoing")
              (neo-git-push)
              (neo-git-check-wait (lambda ()
                                    (and (not neo-git--mutation)
                                         (not neo-git--refresh-process)
                                         (not neo-git--refresh-timer))))
              (neo-git-check-call "-C" clone "pull" "--ff-only" "-q")
              (cl-assert (equal (string-trim (car (process-lines (neo-git--executable) "-C" clone
                                                                 "show" (concat "origin/" branch ":outgoing.txt"))))
                                "from local"))
              ;; Clone pushes a commit; the UI fetches it, then pulls it on an untracked branch.
              (with-temp-file (expand-file-name "incoming.txt" clone) (insert "from clone\n"))
              (neo-git-check-call "-C" clone "add" "--" "incoming.txt")
              (neo-git-check-call "-C" clone "commit" "-qm" "incoming")
              (neo-git-check-call "-C" clone "push" "-q" "origin" branch)
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (_prompt choices &rest _)
                           (cl-assert (member "origin" choices))
                           "origin")))
                (neo-git-fetch))
              (neo-git-check-wait (lambda ()
                                    (and (not neo-git--mutation)
                                         (not neo-git--refresh-process)
                                         (not neo-git--refresh-timer))))
              (cl-assert (equal (string-trim (car (process-lines (neo-git--executable) "-C" root
                                                                 "show" (concat "origin/" branch ":incoming.txt"))))
                                "from clone"))
              (neo-git-check-call "switch" "-c" "no-track")
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (_prompt choices &rest _)
                           (cl-assert (member "origin" choices))
                           "origin"))
                        ((symbol-function 'read-string) (lambda (&rest _)
                                                          branch)))
                (neo-git-pull))
              (neo-git-check-wait (lambda ()
                                    (and (not neo-git--mutation)
                                         (not neo-git--refresh-process)
                                         (not neo-git--refresh-timer))))
              (cl-assert (file-exists-p (expand-file-name "incoming.txt" root)))
              ;; Upstream-less push prompts for and records the explicit destination.
              (neo-git-check-call "switch" "-c" "local-only")
              (with-temp-file "local-only.txt" (insert "explicit target\n"))
              (neo-git-check-call "add" "--" "local-only.txt")
              (neo-git-check-call "commit" "-qm" "local only")
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (_prompt choices &rest _)
                           (cl-assert (member "origin" choices))
                           "origin"))
                        ((symbol-function 'read-string) (lambda (&rest _)
                                                          "local-only")))
                (neo-git-push))
              (neo-git-check-wait (lambda ()
                                    (and (not neo-git--mutation)
                                         (not neo-git--refresh-process)
                                         (not neo-git--refresh-timer))))
              (cl-assert (equal (string-trim (car (process-lines (neo-git--executable) "-C" root
                                                                 "rev-parse" "--abbrev-ref" "--symbolic-full-name" "@{upstream}")))
                                "origin/local-only"))
              (neo-git-check-call "checkout" "--detach" "HEAD")
              (let ((rejected nil))
                (condition-case nil (neo-git-pull) (user-error (setq rejected t)))
                (cl-assert rejected))))))
    (when (get-buffer status-buffer)
      (with-current-buffer status-buffer
        (neo-git-quit))
      (kill-buffer status-buffer))
    (when (get-buffer "*Neo Git Check Diff*")
      (kill-buffer "*Neo Git Check Diff*"))
    (delete-directory root t)))

(let* ((root (make-temp-file "neo-git-unborn-" t))
       (default-directory (file-name-as-directory root))
       (name "new file.txt")
       (status-buffer nil))
  (unwind-protect
      (progn
        (neo-git-check-call "init" "-q")
        (neo-git-check-call "config" "user.name" "Neo Git Check")
        (neo-git-check-call "config" "user.email" "neo-git-check@example.invalid")
        (neo-git-check-call "config" "commit.gpgsign" "false")
        (with-temp-file name (insert "indexed\n"))
        (neo-git-check-call "add" "--" name)
        (with-temp-file name (insert "indexed\nworking\n"))
        (setq status-buffer (format "*Neo Git: %s*" (directory-file-name root)))
        (neo-git-status)
        (neo-git-check-wait
         (lambda ()
           (and (get-buffer status-buffer)
                (with-current-buffer status-buffer
                  (and neo-git-state (not neo-git--refresh-process)
                       (not neo-git--refresh-timer))))))
        (with-current-buffer status-buffer
          (cl-assert (equal (plist-get neo-git-state :oid) "(initial)"))
          (let ((position (cl-find-if (lambda (position)
                                        (eq (plist-get (get-text-property position 'neo-git-entry) :kind)
                                            'staged))
                                      (neo-git--row-positions))))
            (cl-assert position)
            (goto-char position)
            (neo-git-stage-toggle))
          (neo-git-check-wait (lambda ()
                                (and (not neo-git--mutation)
                                     (not neo-git--refresh-process)
                                     (not neo-git--refresh-timer)
                                     (not (seq-some (lambda (entry)
                                                      (eq (plist-get entry :kind) 'staged))
                                                    neo-git-entries))))))
        (cl-assert (equal (with-temp-buffer
                            (insert-file-contents (expand-file-name name root))
                            (buffer-string))
                          "indexed\nworking\n")))
    (when (get-buffer status-buffer)
      (with-current-buffer status-buffer
        (neo-git-quit))
      (kill-buffer status-buffer))
    (delete-directory root t)))

(defun neo-git-check-partial-patch (root path kind needle operation &optional mode)
  (let* ((arguments (append (list "-C" root)
                            (neo-git--diff-arguments path kind)))
         (diff (apply #'neo-git-check-output arguments))
         bounds)
    (with-temp-buffer
      (insert diff)
      (goto-char (point-min))
      (unless (search-forward needle nil t)
        (error "Changed line %S missing from diff: %s" needle diff))
      (let ((line (line-number-at-pos)))
        (setq bounds (cons line line))))
    (neo-git--partial-build-patch (neo-git--partial-hunks diff) bounds (or mode 'line) operation)))

(let* ((root (make-temp-file "neo-git-partial-edge-" t))
       (default-directory (file-name-as-directory root))
       (path "partial.txt")
       (file (expand-file-name path root))
       (original-lines (cl-loop for n from 1 to 24
                                collect (cond ((= n 2) "old-first")
                                              ((= n 12) "old-middle")
                                              ((= n 24) "old-tail")
                                              (t (format "context-%02d" n)))))
       (working-lines (copy-sequence original-lines))
       (original (mapconcat #'identity original-lines "\r\n"))
       (working nil)
       (worktree-bytes nil))
  (unwind-protect
      (progn
        (neo-git-check-call "init" "-q")
        (neo-git-check-call "config" "user.name" "Neo Git Check")
        (neo-git-check-call "config" "user.email" "neo-git-check@example.invalid")
        (neo-git-check-call "config" "commit.gpgsign" "false")
        (neo-git-check-call "config" "core.autocrlf" "false")
        (setf (nth 1 working-lines) "新しい first"
              (nth 11 working-lines) "新しい middle"
              (nth 23 working-lines) "新しい tail")
        (setq working (mapconcat #'identity working-lines "\r\n"))
        (neo-git-check-write-utf8 file original)
        (neo-git-check-call "add" "--" path)
        (neo-git-check-call "commit" "-qm" "partial edge baseline")
        (neo-git-check-write-utf8 file working)
        (setq worktree-bytes (neo-git-check-file-bytes file))
        ;; Select the middle and final hunks only; keep the earlier hunk out.
        (neo-git-check-apply-patch
         root (neo-git-check-partial-patch root path 'unstaged "+新しい middle" 'stage) nil)
        (neo-git-check-apply-patch
         root (neo-git-check-partial-patch root path 'unstaged "+新しい tail" 'stage 'hunk) nil)
        (let ((expected (append (cl-subseq original-lines 0 12)
                                (list "新しい middle")
                                (cl-subseq original-lines 12 23)
                                (list "新しい tail"))))
          (cl-assert (equal (neo-git-check-bytes "-C" root "show" (concat ":" path))
                            (encode-coding-string
                             (mapconcat #'identity expected "\r\n") 'utf-8-unix))
                     nil "Partial hunks must preserve CRLF and a missing final newline; actual=%S expected=%S"
                     (neo-git-check-bytes "-C" root "show" (concat ":" path))
                     (encode-coding-string
                      (mapconcat #'identity expected "\r\n") 'utf-8-unix)))
        (cl-assert (equal (neo-git-check-file-bytes file) worktree-bytes)
                   nil "Partial staging must not alter worktree bytes")
        ;; Reverse only the selected middle addition, leaving the final hunk staged.
        (neo-git-check-apply-patch
         root (neo-git-check-partial-patch root path 'staged "+新しい middle" 'unstage) t)
        (let ((expected (copy-sequence original-lines)))
          (setf (nth 23 expected) "新しい tail")
          (cl-assert (equal (neo-git-check-bytes "-C" root "show" (concat ":" path))
                            (encode-coding-string
                             (mapconcat #'identity expected "\r\n") 'utf-8-unix))
                     nil "Unstaging one later hunk must preserve the other staged hunk"))
        ;; A lock failure must be atomic for both index and worktree.
        (let* ((patch (neo-git-check-partial-patch root path 'unstaged "+新しい first" 'stage))
               (before-index (neo-git-check-bytes "-C" root "show" (concat ":" path)))
               (lock (expand-file-name ".git/index.lock" root))
               (coding-system-for-write 'utf-8-unix))
          (write-region "locked" nil lock nil 'silent)
          (unwind-protect
              (let ((failed nil))
                (condition-case nil
                    (neo-git-check-apply-patch root patch nil)
                  (error (setq failed t)))
                (cl-assert failed nil "Git apply should fail while index.lock exists")
                (cl-assert (equal before-index
                                  (neo-git-check-bytes "-C" root "show" (concat ":" path))))
                (cl-assert (equal worktree-bytes (neo-git-check-file-bytes file)))
            (when (file-exists-p lock) (delete-file lock))))
        ;; Partial hunks of staged whole-file additions/deletions are rejected.
        (with-temp-file "added.txt" (insert "first\nsecond\n"))
        (neo-git-check-call "add" "--" "added.txt")
        (let ((rejected nil)
              (diff (neo-git-check-output "-C" root "diff" "--cached" "--no-ext-diff"
                                          "--no-color" "--no-textconv" "--src-prefix=a/"
                                          "--dst-prefix=b/" "--unified=3" "--" "added.txt")))
          (condition-case nil
              (neo-git--partial-build-patch
               (neo-git--partial-hunks diff)
               (with-temp-buffer (insert diff) (goto-char (point-min))
                                 (search-forward "+first")
                                 (let ((line (line-number-at-pos))) (cons line line)))
               'line 'unstage)
            (user-error (setq rejected t)))
          (cl-assert rejected nil "Partial unstage of a new file must be rejected"))
        (with-temp-file "deleted.txt" (insert "old one\nold two\n"))
        (neo-git-check-call "add" "--" "deleted.txt")
        (neo-git-check-call "commit" "-qm" "deletion baseline")
        (neo-git-check-call "rm" "--" "deleted.txt")
        (let ((rejected nil)
              (diff (neo-git-check-output "-C" root "diff" "--cached" "--no-ext-diff"
                                          "--no-color" "--no-textconv" "--src-prefix=a/"
                                          "--dst-prefix=b/" "--unified=3" "--" "deleted.txt")))
          (condition-case nil
              (neo-git--partial-build-patch
               (neo-git--partial-hunks diff)
               (with-temp-buffer (insert diff) (goto-char (point-min))
                                 (search-forward "-old one")
                                 (let ((line (line-number-at-pos))) (cons line line)))
               'line 'unstage)
            (user-error (setq rejected t)))
          (cl-assert rejected nil "Partial unstage of a deleted file must be rejected"))
        ;; Discard reverts only the selected unstaged hunk in the worktree.
        (let ((before-index (neo-git-check-bytes "-C" root "show" (concat ":" path)))
              (expected (copy-sequence working-lines)))
          (neo-git-check-apply-patch
           root (neo-git-check-partial-patch root path 'unstaged "+新しい middle" 'unstage 'hunk) t t)
          (setf (nth 11 expected) "old-middle")
          (cl-assert (equal (neo-git-check-file-bytes file)
                            (encode-coding-string
                             (mapconcat #'identity expected "\r\n") 'utf-8-unix))
                     nil "Discard must revert only the selected worktree hunk")
          (cl-assert (equal before-index
                            (neo-git-check-bytes "-C" root "show" (concat ":" path)))
                     nil "Discard must not alter the index")))
    (delete-directory root t))))

(neo-git-benchmark-stop)
(cl-assert (> neo-git-benchmark-process-count 0))
(let ((file (make-temp-file "neo-git-benchmark-")))
  (unwind-protect
      (progn
        (neo-git-benchmark-write file)
        (let ((result (json-read-file file)))
          (cl-assert (> (alist-get 'process_calls result) 0))
          (cl-assert (vectorp (alist-get 'events result))))
        (princ (format "NEO_GIT_CHECK=PASS process_calls=%d max_active=%d\n"
                       neo-git-benchmark-process-count neo-git-benchmark-max-active-processes)))
    (delete-file file)))
;;; check-git.el ends here
